/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    pages: Page;
    posts: Post;
    categories: Category;
    forms: Form;
    'form-submissions': FormSubmission;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    posts: PostsSelect<false> | PostsSelect<true>;
    categories: CategoriesSelect<false> | CategoriesSelect<true>;
    forms: FormsSelect<false> | FormsSelect<true>;
    'form-submissions': FormSubmissionsSelect<false> | FormSubmissionsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    header: Header;
    footer: Footer;
    company: Company;
    'site-settings': SiteSettings;
  };
  globalsSelect: {
    header: HeaderSelect<false> | HeaderSelect<true>;
    footer: FooterSelect<false> | FooterSelect<true>;
    company: CompanySelect<false> | CompanySelect<true>;
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  title: string;
  /**
   * Use 'home' para a página inicial. Sem acento (ex.: solucoes).
   */
  slug: string;
  layout?:
    | (
        | HeroBlock
        | StatsBlock
        | ValuesMarqueeBlock
        | WordsSectionBlock
        | PillarsBlock
        | TimelineBlock
        | SolucoesBentoBlock
        | SolutionSplitBlock
        | ProdutosGridBlock
        | FeatureGridBlock
        | GaranteBlock
        | CitiesBlock
        | HumanQuoteBlock
        | PrestacaoBlock
        | TecnologiaRoadmapBlock
        | ClubeBeneficiosBlock
        | SociosBlock
        | RegistrosBlock
        | AppShowcaseBlock
        | TestimonialsBlock
        | FaqBlock
        | CTABandBlock
        | RichTextBlock
        | BlogListBlock
        | ShowcaseBlock
        | BenefitsBlock
        | ContactInfoBlock
        | FormEmbedBlock
      )[]
    | null;
  publishedAt?: string | null;
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "HeroBlock".
 */
export interface HeroBlock {
  eyebrow?: string | null;
  headline: string;
  subhead?: string | null;
  /**
   * Coluna de vidro à direita do hero (`.hero-tagbox`), ex.: "Condomínios. Métricas. Organização." Opcional — sem valor, o layout fica de 1 coluna como antes.
   */
  tag?: string | null;
  video?: (number | null) | Media;
  poster?: (number | null) | Media;
  /**
   * Ativa o tratamento `.page-hero` do ref (ex.: `_reference/solucoes.html:87-107`): altura reduzida (74dvh), a imagem de `poster` com opacidade 0.5 e um gradiente `::after` escuro por cima para dar contraste ao texto. Só tem efeito sem `video` (o hero com vídeo, ex. home, não muda). Sem isso marcado, o herói mantém o comportamento atual (100dvh, sem overlay). Os valores exatos (74dvh, opacidade, paradas do gradiente) são os de `/solucoes` — se outra página precisar deste tratamento com números diferentes do ref dela, este campo precisa virar configurável por instância.
   */
  pageHeroOverlay?: boolean | null;
  ctas?:
    | {
        label: string;
        href: string;
        variant?: ('primary' | 'ghost' | 'white' | 'glass') | null;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'hero';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "StatsBlock".
 */
export interface StatsBlock {
  eyebrow?: string | null;
  title?: string | null;
  items?:
    | {
        value: number;
        prefix?: string | null;
        suffix?: string | null;
        label: string;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'stats';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ValuesMarqueeBlock".
 */
export interface ValuesMarqueeBlock {
  /**
   * Valores exibidos na faixa (ex.: TRANSPARÊNCIA, RETIDÃO, DINÂMICA).
   */
  items: string[];
  /**
   * Divisor entre os valores. Default "/".
   */
  separator?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'valuesMarquee';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "WordsSectionBlock".
 */
export interface WordsSectionBlock {
  eyebrow?: string | null;
  text: string;
  id?: string | null;
  blockName?: string | null;
  blockType: 'wordsSection';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "PillarsBlock".
 */
export interface PillarsBlock {
  items: {
    glyph?: string | null;
    title: string;
    text: string;
    id?: string | null;
  }[];
  id?: string | null;
  blockName?: string | null;
  blockType: 'pillars';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TimelineBlock".
 */
export interface TimelineBlock {
  eyebrow?: string | null;
  title?: string | null;
  text?: string | null;
  items: {
    date: string;
    title: string;
    text: string;
    image?: (number | null) | Media;
    /**
     * Marca o cartão atual (glow), equivalente a .tl-item.now no ref.
     */
    now?: boolean | null;
    id?: string | null;
  }[];
  id?: string | null;
  blockName?: string | null;
  blockType: 'timeline';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "SolucoesBentoBlock".
 */
export interface SolucoesBentoBlock {
  eyebrow?: string | null;
  title: string;
  cards: {
    image: number | Media;
    tag?: string | null;
    title: string;
    text: string;
    href?: string | null;
    /**
     * Ocupa o card alto (coluna larga) do bento.
     */
    tall?: boolean | null;
    id?: string | null;
  }[];
  id?: string | null;
  blockName?: string | null;
  blockType: 'solucoesBento';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "SolutionSplitBlock".
 */
export interface SolutionSplitBlock {
  items: {
    variant?: ('split' | 'assoc') | null;
    kicker?: string | null;
    title: string;
    text?: string | null;
    /**
     * Pills de serviços incluídos (.svc-tags) — só na variante split.
     */
    tags?:
      | {
          label: string;
          id?: string | null;
        }[]
      | null;
    image: number | Media;
    /**
     * Inverte o lado: imagem à esquerda, texto à direita. Só na variante split.
     */
    reversed?: boolean | null;
    /**
     * Link-arrow do .assoc-body — só na variante full-bleed.
     */
    ctaLabel?: string | null;
    ctaHref?: string | null;
    id?: string | null;
  }[];
  id?: string | null;
  blockName?: string | null;
  blockType: 'solutionSplit';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ProdutosGridBlock".
 */
export interface ProdutosGridBlock {
  eyebrow?: string | null;
  title: string;
  cards: {
    image: number | Media;
    theme: 'on-white' | 'on-navy' | 'on-deep';
    tag?: string | null;
    title: string;
    text: string;
    href?: string | null;
    id?: string | null;
  }[];
  id?: string | null;
  blockName?: string | null;
  blockType: 'produtosGrid';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FeatureGridBlock".
 */
export interface FeatureGridBlock {
  eyebrow?: string | null;
  title?: string | null;
  features?:
    | {
        icon?: string | null;
        title: string;
        description: string;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'featureGrid';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "GaranteBlock".
 */
export interface GaranteBlock {
  eyebrow?: string | null;
  title: string;
  text?: string | null;
  video?: (number | null) | Media;
  poster?: (number | null) | Media;
  features?:
    | {
        title: string;
        description: string;
        id?: string | null;
      }[]
    | null;
  cta?: {
    label?: string | null;
    href?: string | null;
  };
  /**
   * Chip de vidro "1%" da banda com vídeo (`.pct-chip`), ex.: valor "1%" + legenda.
   */
  priceChip?: {
    value?: string | null;
    label?: string | null;
  };
  note?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'garante';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CitiesBlock".
 */
export interface CitiesBlock {
  eyebrow?: string | null;
  title?: string | null;
  items?:
    | {
        city: string;
        uf: string;
        role?: string | null;
        image?: (number | null) | Media;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'cities';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "HumanQuoteBlock".
 */
export interface HumanQuoteBlock {
  quote: string;
  author?: string | null;
  image: number | Media;
  caption?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'humanQuote';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "PrestacaoBlock".
 */
export interface PrestacaoBlock {
  eyebrow?: string | null;
  title: string;
  text?: string | null;
  image: number | Media;
  list: {
    icon?: string | null;
    title: string;
    text: string;
    id?: string | null;
  }[];
  id?: string | null;
  blockName?: string | null;
  blockType: 'prestacao';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TecnologiaRoadmapBlock".
 */
export interface TecnologiaRoadmapBlock {
  eyebrow?: string | null;
  title: string;
  text?: string | null;
  intro: {
    /**
     * Opcional. Ex.: semog-one.webp (monitor com o ERP).
     */
    image?: (number | null) | Media;
    name: string;
    description: string;
    tags?:
      | {
          label: string;
          id?: string | null;
        }[]
      | null;
  };
  roadmapLabel?: string | null;
  steps: {
    title: string;
    text: string;
    status: string;
    /**
     * Destaca o status como "no ar" (`.status.live`).
     */
    live?: boolean | null;
    id?: string | null;
  }[];
  id?: string | null;
  blockName?: string | null;
  blockType: 'tecnologiaRoadmap';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ClubeBeneficiosBlock".
 */
export interface ClubeBeneficiosBlock {
  eyebrow?: string | null;
  title: string;
  text?: string | null;
  items: {
    icon?: string | null;
    title: string;
    text: string;
    id?: string | null;
  }[];
  note?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'clubeBeneficios';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "SociosBlock".
 */
export interface SociosBlock {
  eyebrow?: string | null;
  title: string;
  text?: string | null;
  items: {
    title: string;
    text: string;
    id?: string | null;
  }[];
  image: number | Media;
  caption?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'socios';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "RegistrosBlock".
 */
export interface RegistrosBlock {
  title?: string | null;
  items?:
    | {
        label: string;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'registros';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "AppShowcaseBlock".
 */
export interface AppShowcaseBlock {
  eyebrow?: string | null;
  title: string;
  text?: string | null;
  image?: (number | null) | Media;
  features?:
    | {
        title: string;
        description: string;
        id?: string | null;
      }[]
    | null;
  cta?: {
    label?: string | null;
    href?: string | null;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'appShowcase';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TestimonialsBlock".
 */
export interface TestimonialsBlock {
  eyebrow?: string | null;
  title?: string | null;
  items?:
    | {
        quote: string;
        author: string;
        role?: string | null;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'testimonials';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FaqBlock".
 */
export interface FaqBlock {
  eyebrow?: string | null;
  title?: string | null;
  items?:
    | {
        question: string;
        answer: string;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'faq';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CTABandBlock".
 */
export interface CTABandBlock {
  variant?: ('band' | 'centered') | null;
  title: string;
  text?: string | null;
  cta: {
    label: string;
    href: string;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'ctaBand';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "RichTextBlock".
 */
export interface RichTextBlock {
  content?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'richText';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "BlogListBlock".
 */
export interface BlogListBlock {
  title?: string | null;
  /**
   * Quantidade de posts a exibir (padrão 6).
   */
  limit?: number | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'blogList';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ShowcaseBlock".
 */
export interface ShowcaseBlock {
  eyebrow?: string | null;
  title: string;
  text?: string | null;
  features?:
    | {
        title: string;
        description: string;
        id?: string | null;
      }[]
    | null;
  cta?: {
    label?: string | null;
    href?: string | null;
  };
  mediaSide?: ('left' | 'right') | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'showcase';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "BenefitsBlock".
 */
export interface BenefitsBlock {
  variant?: ('grid' | 'bento') | null;
  eyebrow?: string | null;
  title?: string | null;
  /**
   * Trecho final de `title` a destacar em gradiente (.gx), ex.: "Semog assume." em "O que muda quando a Semog assume." Só no variant bento.
   */
  titleAccent?: string | null;
  items?:
    | {
        title: string;
        description: string;
        /**
         * Número gigante da célula (.num), ex.: "24h". Só no variant bento.
         */
        value?: string | null;
        /**
         * Foto de fundo da célula (c4). Só no variant bento.
         */
        image?: (number | null) | Media;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'benefits';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ContactInfoBlock".
 */
export interface ContactInfoBlock {
  eyebrow?: string | null;
  title?: string | null;
  items?:
    | {
        city: string;
        uf: string;
        address: string;
        phone: string;
        id?: string | null;
      }[]
    | null;
  whatsapp?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'contactInfo';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FormEmbedBlock".
 */
export interface FormEmbedBlock {
  formType: 'contato' | 'proposta';
  eyebrow?: string | null;
  title?: string | null;
  text?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'formEmbed';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts".
 */
export interface Post {
  id: number;
  title: string;
  slug: string;
  heroImage?: (number | null) | Media;
  excerpt?: string | null;
  content?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  category?: (number | null) | Category;
  publishedAt?: string | null;
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories".
 */
export interface Category {
  id: number;
  title: string;
  slug: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "forms".
 */
export interface Form {
  id: number;
  title: string;
  fields?:
    | (
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            required?: boolean | null;
            defaultValue?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'checkbox';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'email';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: number | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'number';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: string | null;
            placeholder?: string | null;
            options?:
              | {
                  label: string;
                  value: string;
                  id?: string | null;
                }[]
              | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'select';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: string | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'text';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: string | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'textarea';
          }
      )[]
    | null;
  submitButtonLabel?: string | null;
  confirmationType?: ('message' | 'redirect') | null;
  confirmationMessage?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  redirect?: {
    url: string;
  };
  emails?:
    | {
        emailTo?: string | null;
        cc?: string | null;
        bcc?: string | null;
        replyTo?: string | null;
        emailFrom?: string | null;
        subject: string;
        message?: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        } | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "form-submissions".
 */
export interface FormSubmission {
  id: number;
  form: number | Form;
  submissionData?:
    | {
        field: string;
        value: string;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'posts';
        value: number | Post;
      } | null)
    | ({
        relationTo: 'categories';
        value: number | Category;
      } | null)
    | ({
        relationTo: 'forms';
        value: number | Form;
      } | null)
    | ({
        relationTo: 'form-submissions';
        value: number | FormSubmission;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  layout?:
    | T
    | {
        hero?: T | HeroBlockSelect<T>;
        stats?: T | StatsBlockSelect<T>;
        valuesMarquee?: T | ValuesMarqueeBlockSelect<T>;
        wordsSection?: T | WordsSectionBlockSelect<T>;
        pillars?: T | PillarsBlockSelect<T>;
        timeline?: T | TimelineBlockSelect<T>;
        solucoesBento?: T | SolucoesBentoBlockSelect<T>;
        solutionSplit?: T | SolutionSplitBlockSelect<T>;
        produtosGrid?: T | ProdutosGridBlockSelect<T>;
        featureGrid?: T | FeatureGridBlockSelect<T>;
        garante?: T | GaranteBlockSelect<T>;
        cities?: T | CitiesBlockSelect<T>;
        humanQuote?: T | HumanQuoteBlockSelect<T>;
        prestacao?: T | PrestacaoBlockSelect<T>;
        tecnologiaRoadmap?: T | TecnologiaRoadmapBlockSelect<T>;
        clubeBeneficios?: T | ClubeBeneficiosBlockSelect<T>;
        socios?: T | SociosBlockSelect<T>;
        registros?: T | RegistrosBlockSelect<T>;
        appShowcase?: T | AppShowcaseBlockSelect<T>;
        testimonials?: T | TestimonialsBlockSelect<T>;
        faq?: T | FaqBlockSelect<T>;
        ctaBand?: T | CTABandBlockSelect<T>;
        richText?: T | RichTextBlockSelect<T>;
        blogList?: T | BlogListBlockSelect<T>;
        showcase?: T | ShowcaseBlockSelect<T>;
        benefits?: T | BenefitsBlockSelect<T>;
        contactInfo?: T | ContactInfoBlockSelect<T>;
        formEmbed?: T | FormEmbedBlockSelect<T>;
      };
  publishedAt?: T;
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "HeroBlock_select".
 */
export interface HeroBlockSelect<T extends boolean = true> {
  eyebrow?: T;
  headline?: T;
  subhead?: T;
  tag?: T;
  video?: T;
  poster?: T;
  pageHeroOverlay?: T;
  ctas?:
    | T
    | {
        label?: T;
        href?: T;
        variant?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "StatsBlock_select".
 */
export interface StatsBlockSelect<T extends boolean = true> {
  eyebrow?: T;
  title?: T;
  items?:
    | T
    | {
        value?: T;
        prefix?: T;
        suffix?: T;
        label?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ValuesMarqueeBlock_select".
 */
export interface ValuesMarqueeBlockSelect<T extends boolean = true> {
  items?: T;
  separator?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "WordsSectionBlock_select".
 */
export interface WordsSectionBlockSelect<T extends boolean = true> {
  eyebrow?: T;
  text?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "PillarsBlock_select".
 */
export interface PillarsBlockSelect<T extends boolean = true> {
  items?:
    | T
    | {
        glyph?: T;
        title?: T;
        text?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TimelineBlock_select".
 */
export interface TimelineBlockSelect<T extends boolean = true> {
  eyebrow?: T;
  title?: T;
  text?: T;
  items?:
    | T
    | {
        date?: T;
        title?: T;
        text?: T;
        image?: T;
        now?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "SolucoesBentoBlock_select".
 */
export interface SolucoesBentoBlockSelect<T extends boolean = true> {
  eyebrow?: T;
  title?: T;
  cards?:
    | T
    | {
        image?: T;
        tag?: T;
        title?: T;
        text?: T;
        href?: T;
        tall?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "SolutionSplitBlock_select".
 */
export interface SolutionSplitBlockSelect<T extends boolean = true> {
  items?:
    | T
    | {
        variant?: T;
        kicker?: T;
        title?: T;
        text?: T;
        tags?:
          | T
          | {
              label?: T;
              id?: T;
            };
        image?: T;
        reversed?: T;
        ctaLabel?: T;
        ctaHref?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ProdutosGridBlock_select".
 */
export interface ProdutosGridBlockSelect<T extends boolean = true> {
  eyebrow?: T;
  title?: T;
  cards?:
    | T
    | {
        image?: T;
        theme?: T;
        tag?: T;
        title?: T;
        text?: T;
        href?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FeatureGridBlock_select".
 */
export interface FeatureGridBlockSelect<T extends boolean = true> {
  eyebrow?: T;
  title?: T;
  features?:
    | T
    | {
        icon?: T;
        title?: T;
        description?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "GaranteBlock_select".
 */
export interface GaranteBlockSelect<T extends boolean = true> {
  eyebrow?: T;
  title?: T;
  text?: T;
  video?: T;
  poster?: T;
  features?:
    | T
    | {
        title?: T;
        description?: T;
        id?: T;
      };
  cta?:
    | T
    | {
        label?: T;
        href?: T;
      };
  priceChip?:
    | T
    | {
        value?: T;
        label?: T;
      };
  note?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CitiesBlock_select".
 */
export interface CitiesBlockSelect<T extends boolean = true> {
  eyebrow?: T;
  title?: T;
  items?:
    | T
    | {
        city?: T;
        uf?: T;
        role?: T;
        image?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "HumanQuoteBlock_select".
 */
export interface HumanQuoteBlockSelect<T extends boolean = true> {
  quote?: T;
  author?: T;
  image?: T;
  caption?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "PrestacaoBlock_select".
 */
export interface PrestacaoBlockSelect<T extends boolean = true> {
  eyebrow?: T;
  title?: T;
  text?: T;
  image?: T;
  list?:
    | T
    | {
        icon?: T;
        title?: T;
        text?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TecnologiaRoadmapBlock_select".
 */
export interface TecnologiaRoadmapBlockSelect<T extends boolean = true> {
  eyebrow?: T;
  title?: T;
  text?: T;
  intro?:
    | T
    | {
        image?: T;
        name?: T;
        description?: T;
        tags?:
          | T
          | {
              label?: T;
              id?: T;
            };
      };
  roadmapLabel?: T;
  steps?:
    | T
    | {
        title?: T;
        text?: T;
        status?: T;
        live?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ClubeBeneficiosBlock_select".
 */
export interface ClubeBeneficiosBlockSelect<T extends boolean = true> {
  eyebrow?: T;
  title?: T;
  text?: T;
  items?:
    | T
    | {
        icon?: T;
        title?: T;
        text?: T;
        id?: T;
      };
  note?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "SociosBlock_select".
 */
export interface SociosBlockSelect<T extends boolean = true> {
  eyebrow?: T;
  title?: T;
  text?: T;
  items?:
    | T
    | {
        title?: T;
        text?: T;
        id?: T;
      };
  image?: T;
  caption?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "RegistrosBlock_select".
 */
export interface RegistrosBlockSelect<T extends boolean = true> {
  title?: T;
  items?:
    | T
    | {
        label?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "AppShowcaseBlock_select".
 */
export interface AppShowcaseBlockSelect<T extends boolean = true> {
  eyebrow?: T;
  title?: T;
  text?: T;
  image?: T;
  features?:
    | T
    | {
        title?: T;
        description?: T;
        id?: T;
      };
  cta?:
    | T
    | {
        label?: T;
        href?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TestimonialsBlock_select".
 */
export interface TestimonialsBlockSelect<T extends boolean = true> {
  eyebrow?: T;
  title?: T;
  items?:
    | T
    | {
        quote?: T;
        author?: T;
        role?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FaqBlock_select".
 */
export interface FaqBlockSelect<T extends boolean = true> {
  eyebrow?: T;
  title?: T;
  items?:
    | T
    | {
        question?: T;
        answer?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CTABandBlock_select".
 */
export interface CTABandBlockSelect<T extends boolean = true> {
  variant?: T;
  title?: T;
  text?: T;
  cta?:
    | T
    | {
        label?: T;
        href?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "RichTextBlock_select".
 */
export interface RichTextBlockSelect<T extends boolean = true> {
  content?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "BlogListBlock_select".
 */
export interface BlogListBlockSelect<T extends boolean = true> {
  title?: T;
  limit?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ShowcaseBlock_select".
 */
export interface ShowcaseBlockSelect<T extends boolean = true> {
  eyebrow?: T;
  title?: T;
  text?: T;
  features?:
    | T
    | {
        title?: T;
        description?: T;
        id?: T;
      };
  cta?:
    | T
    | {
        label?: T;
        href?: T;
      };
  mediaSide?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "BenefitsBlock_select".
 */
export interface BenefitsBlockSelect<T extends boolean = true> {
  variant?: T;
  eyebrow?: T;
  title?: T;
  titleAccent?: T;
  items?:
    | T
    | {
        title?: T;
        description?: T;
        value?: T;
        image?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ContactInfoBlock_select".
 */
export interface ContactInfoBlockSelect<T extends boolean = true> {
  eyebrow?: T;
  title?: T;
  items?:
    | T
    | {
        city?: T;
        uf?: T;
        address?: T;
        phone?: T;
        id?: T;
      };
  whatsapp?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FormEmbedBlock_select".
 */
export interface FormEmbedBlockSelect<T extends boolean = true> {
  formType?: T;
  eyebrow?: T;
  title?: T;
  text?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts_select".
 */
export interface PostsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  heroImage?: T;
  excerpt?: T;
  content?: T;
  category?: T;
  publishedAt?: T;
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories_select".
 */
export interface CategoriesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "forms_select".
 */
export interface FormsSelect<T extends boolean = true> {
  title?: T;
  fields?:
    | T
    | {
        checkbox?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              required?: T;
              defaultValue?: T;
              id?: T;
              blockName?: T;
            };
        email?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        number?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        select?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              placeholder?: T;
              options?:
                | T
                | {
                    label?: T;
                    value?: T;
                    id?: T;
                  };
              required?: T;
              id?: T;
              blockName?: T;
            };
        text?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        textarea?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
      };
  submitButtonLabel?: T;
  confirmationType?: T;
  confirmationMessage?: T;
  redirect?:
    | T
    | {
        url?: T;
      };
  emails?:
    | T
    | {
        emailTo?: T;
        cc?: T;
        bcc?: T;
        replyTo?: T;
        emailFrom?: T;
        subject?: T;
        message?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "form-submissions_select".
 */
export interface FormSubmissionsSelect<T extends boolean = true> {
  form?: T;
  submissionData?:
    | T
    | {
        field?: T;
        value?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header".
 */
export interface Header {
  id: number;
  navItems?:
    | {
        label: string;
        href: string;
        id?: string | null;
      }[]
    | null;
  cta?: {
    label?: string | null;
    href?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer".
 */
export interface Footer {
  id: number;
  footCta?: {
    slogan?: string | null;
    sloganEm?: string | null;
    cta?: {
      label?: string | null;
      href?: string | null;
    };
  };
  columns?:
    | {
        title: string;
        links?:
          | {
              label: string;
              href: string;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  legalLinks?:
    | {
        label: string;
        href: string;
        id?: string | null;
      }[]
    | null;
  bottomText?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "company".
 */
export interface Company {
  id: number;
  addresses?:
    | {
        city: string;
        uf: string;
        address: string;
        phone?: string | null;
        creci?: string | null;
        abadi?: string | null;
        secovi?: string | null;
        id?: string | null;
      }[]
    | null;
  whatsapp?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSettings {
  id: number;
  defaultTitle?: string | null;
  defaultDescription?: string | null;
  ogImage?: (number | null) | Media;
  social?: {
    instagram?: string | null;
    linkedin?: string | null;
    facebook?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header_select".
 */
export interface HeaderSelect<T extends boolean = true> {
  navItems?:
    | T
    | {
        label?: T;
        href?: T;
        id?: T;
      };
  cta?:
    | T
    | {
        label?: T;
        href?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer_select".
 */
export interface FooterSelect<T extends boolean = true> {
  footCta?:
    | T
    | {
        slogan?: T;
        sloganEm?: T;
        cta?:
          | T
          | {
              label?: T;
              href?: T;
            };
      };
  columns?:
    | T
    | {
        title?: T;
        links?:
          | T
          | {
              label?: T;
              href?: T;
              id?: T;
            };
        id?: T;
      };
  legalLinks?:
    | T
    | {
        label?: T;
        href?: T;
        id?: T;
      };
  bottomText?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "company_select".
 */
export interface CompanySelect<T extends boolean = true> {
  addresses?:
    | T
    | {
        city?: T;
        uf?: T;
        address?: T;
        phone?: T;
        creci?: T;
        abadi?: T;
        secovi?: T;
        id?: T;
      };
  whatsapp?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  defaultTitle?: T;
  defaultDescription?: T;
  ogImage?: T;
  social?:
    | T
    | {
        instagram?: T;
        linkedin?: T;
        facebook?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}