/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    pages: Page;
    posts: Post;
    categories: Category;
    forms: Form;
    'form-submissions': FormSubmission;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    posts: PostsSelect<false> | PostsSelect<true>;
    categories: CategoriesSelect<false> | CategoriesSelect<true>;
    forms: FormsSelect<false> | FormsSelect<true>;
    'form-submissions': FormSubmissionsSelect<false> | FormSubmissionsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    header: Header;
    footer: Footer;
    company: Company;
    'site-settings': SiteSettings;
  };
  globalsSelect: {
    header: HeaderSelect<false> | HeaderSelect<true>;
    footer: FooterSelect<false> | FooterSelect<true>;
    company: CompanySelect<false> | CompanySelect<true>;
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  title: string;
  /**
   * Use 'home' para a página inicial. Sem acento (ex.: solucoes).
   */
  slug: string;
  layout?:
    | (
        | HeroBlock
        | StatsBlock
        | ValuesMarqueeBlock
        | WordsSectionBlock
        | PillarsBlock
        | TimelineBlock
        | SolucoesBentoBlock
        | SolutionSplitBlock
        | ProdutosGridBlock
        | FeatureGridBlock
        | GaranteBlock
        | CitiesBlock
        | HumanQuoteBlock
        | PrestacaoBlock
        | TecnologiaRoadmapBlock
        | ClubeBeneficiosBlock
        | SociosBlock
        | RegistrosBlock
        | AppShowcaseBlock
        | TestimonialsBlock
        | FaqBlock
        | CTABandBlock
        | CustoChecklistBlock
        | RichTextBlock
        | BlogListBlock
        | BlogFeaturedBlock
        | NewsletterBlock
        | ShowcaseBlock
        | BenefitsBlock
        | ContactInfoBlock
        | FormEmbedBlock
        | PriceMomentBlock
        | CompareBlock
        | PartnerSplitBlock
        | DevQuoteBlock
        | ProcessoTimelineBlock
        | BairrosBlock
        | QuickLinksBlock
        | SelfServeBlock
        | TrustPanelBlock
        | LegalHeroBlock
      )[]
    | null;
  publishedAt?: string | null;
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "HeroBlock".
 */
export interface HeroBlock {
  eyebrow?: string | null;
  headline: string;
  subhead?: string | null;
  /**
   * Coluna de vidro à direita do hero (`.hero-tagbox`), ex.: "Condomínios. Métricas. Organização." Opcional — sem valor, o layout fica de 1 coluna como antes.
   */
  tag?: string | null;
  video?: (number | null) | Media;
  poster?: (number | null) | Media;
  /**
   * Só `gradient` tem efeito próprio: troca o fundo por `GradientBackground` (`src/motion/GradientBackground.tsx`), um gradiente "aurora" animado em canvas, reativo ao mouse, na paleta navy/ice — usado no hero da home no lugar do vídeo. Os outros três valores (inclusive o default `video`, e o vazio dos heróis já existentes antes deste campo) preservam o comportamento anterior inalterado: vídeo+poster se `video` estiver preenchido, senão `pageHeroOverlay`/`poster` como imagem, senão navy sólido — este campo não introduz lógica nova pra eles.
   */
  background?: ('video' | 'gradient' | 'image' | 'plain') | null;
  /**
   * Ativa o tratamento `.page-hero` do ref (ex.: `_reference/solucoes.html:87-107`): altura reduzida, a imagem de `poster` com opacidade reduzida e um gradiente `::after` escuro por cima para dar contraste ao texto. Só tem efeito sem `video` (o hero com vídeo, ex. home, não muda). Sem isso marcado, o herói mantém o comportamento atual (100dvh, sem overlay). Os 4 campos abaixo (`pageHeroMinHeight`/`pageHeroPosterOpacity`/`pageHeroBgPosition`/`pageHeroGradient`) controlam os números exatos — cada `.page-hero` do ref tem seus próprios valores (ex.: `/solucoes` = 74dvh/0.5/"center 65%"; `/administracao-de-condominios` = 88dvh/0.85/"center 40%"); os defaults abaixo são os de `/solucoes`, primeira página a usar este campo.
   */
  pageHeroOverlay?: boolean | null;
  /**
   * Só com `pageHeroOverlay`. `min-height` do `.page-hero` do ref (ex.: `74dvh` em `/solucoes`, `88dvh` em `/administracao-de-condominios`).
   */
  pageHeroMinHeight?: string | null;
  /**
   * Só com `pageHeroOverlay`. Opacidade de `.page-hero .bg` do ref (ex.: `0.5` em `/solucoes`, `0.85` em `/administracao-de-condominios`).
   */
  pageHeroPosterOpacity?: number | null;
  /**
   * Só com `pageHeroOverlay`. `background-position` de `.page-hero .bg` do ref (ex.: `center 65%` em `/solucoes`, `center 40%` em `/administracao-de-condominios`).
   */
  pageHeroBgPosition?: string | null;
  /**
   * Só com `pageHeroOverlay`. Sem `poster`: este é o `background` COMPLETO do próprio `.page-hero` (ex. `_reference/blog.html:40-44`, radial-gradient + `var(--grad-hero)`, sem imagem nenhuma). Com `poster`: é o `background` de `.page-hero::after`, um gradiente escuro por cima da imagem (ex. `/administracao-de-condominios`: `linear-gradient(180deg, rgba(5,8,26,0.45) 0%, rgba(5,8,26,0.15) 45%, rgba(5,8,26,0.85) 100%)`).
   */
  pageHeroGradient?: string | null;
  /**
   * Só com `pageHeroOverlay`. `padding-block` (segundo valor) do `.page-hero` do ref — a maioria das páginas usa `clamp(3rem, 6vw, 4.5rem)` (o default aqui), mas `/blog` e `/contato` usam `clamp(2.5rem, 5vw, 4rem)` (`_reference/blog.html:43`).
   */
  pageHeroPaddingBottom?: string | null;
  /**
   * `max-width` do `h1`, fiel ao `ch` de cada `.hero h1`/`.page-hero h1` do ref (ex.: `16ch` em `/blog`, `/solucoes` e `/administracao-de-condominios`, `15ch` em `/contato` e `/incorporadoras`, `14ch` em `/semog`, `17ch` nas landings de cidade). Funciona em qualquer hero, não só com `pageHeroOverlay`. Deixe em branco para não aplicar nenhum `max-width` (caso do `.hero h1` genérico da home, que no ref não tem `max-width` — só `font-size`).
   */
  pageHeroHeadlineMaxWidth?: string | null;
  ctas?:
    | {
        label: string;
        href: string;
        variant?: ('primary' | 'ghost' | 'white' | 'glass') | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Chip de vidro "1%" do hero de vídeo (`.g-price`), fiel a `_reference/garante.html:94-104` (estilo inline da própria página — distinto do `.pct-chip` do bloco `Garante`, que é o da banda `.g-band-home`). Só tem efeito com `video` preenchido: liga o overlay `::after` (`.g-hero`) e troca o layout de subhead/CTAs para a `.row` (docked à esquerda) + o chip (docked à direita), no lugar do empilhamento padrão. Deixe em branco para o hero de vídeo sem chip (ex.: home).
   */
  priceChip?: {
    value?: string | null;
    label?: string | null;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'hero';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "StatsBlock".
 */
export interface StatsBlock {
  eyebrow?: string | null;
  title?: string | null;
  items?:
    | {
        value: number;
        prefix?: string | null;
        suffix?: string | null;
        label: string;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'stats';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ValuesMarqueeBlock".
 */
export interface ValuesMarqueeBlock {
  variant?: ('values' | 'ticker') | null;
  /**
   * Valores exibidos na faixa (ex.: TRANSPARÊNCIA, RETIDÃO, DINÂMICA).
   */
  items: string[];
  /**
   * Divisor entre os valores. Default "/".
   */
  separator?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'valuesMarquee';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "WordsSectionBlock".
 */
export interface WordsSectionBlock {
  variant?: ('manifesto' | 'problem' | 'argument') | null;
  eyebrow?: string | null;
  /**
   * Aceita `<em>...</em>` embutido para o destaque em ice do ref (`.argument .big em`/`.manifesto .big em`) — `Words` preserva a marcação, ver doc do bloco acima.
   */
  text: string;
  /**
   * Parágrafo de apoio abaixo de `text` (`.argument .sub`), revelado em bloco via `Reveal` (sem scrub). Só usado pelo variant `argument` — ignorado nas outras 2.
   */
  sub?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'wordsSection';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "PillarsBlock".
 */
export interface PillarsBlock {
  eyebrow?: string | null;
  /**
   * Zera o padding-top da seção (`.pillars { padding-top: 0 }` do ref, usado na Home/`semog`). Desmarque quando a página reutilizando este bloco não tem esse zero (ex. `.method` de `/administracao-de-condominios`, `.g-how` de `/garante`).
   */
  tightTop?: boolean | null;
  light?: boolean | null;
  white?: boolean | null;
  /**
   * Tipografia levemente menor (`h3`/`p`), fiel a `.g-step` de `/garante` (vs `.pillar-row` padrão da Home).
   */
  compact?: boolean | null;
  items: {
    glyph?: string | null;
    title: string;
    text: string;
    id?: string | null;
  }[];
  id?: string | null;
  blockName?: string | null;
  blockType: 'pillars';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TimelineBlock".
 */
export interface TimelineBlock {
  eyebrow?: string | null;
  title?: string | null;
  text?: string | null;
  items: {
    date: string;
    title: string;
    text: string;
    image?: (number | null) | Media;
    /**
     * Marca o cartão atual (glow), equivalente a .tl-item.now no ref.
     */
    now?: boolean | null;
    id?: string | null;
  }[];
  id?: string | null;
  blockName?: string | null;
  blockType: 'timeline';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "SolucoesBentoBlock".
 */
export interface SolucoesBentoBlock {
  eyebrow?: string | null;
  title: string;
  cards: {
    image: number | Media;
    tag?: string | null;
    title: string;
    text: string;
    href?: string | null;
    /**
     * Ocupa o card alto (coluna larga) do bento.
     */
    tall?: boolean | null;
    id?: string | null;
  }[];
  id?: string | null;
  blockName?: string | null;
  blockType: 'solucoesBento';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "SolutionSplitBlock".
 */
export interface SolutionSplitBlock {
  items: {
    variant?: ('split' | 'assoc') | null;
    kicker?: string | null;
    title: string;
    text?: string | null;
    /**
     * Pills de serviços incluídos (.svc-tags) — só na variante split.
     */
    tags?:
      | {
          label: string;
          id?: string | null;
        }[]
      | null;
    image: number | Media;
    /**
     * Inverte o lado: imagem à esquerda, texto à direita. Só na variante split.
     */
    reversed?: boolean | null;
    /**
     * Link-arrow do .assoc-body — só na variante full-bleed.
     */
    ctaLabel?: string | null;
    ctaHref?: string | null;
    id?: string | null;
  }[];
  id?: string | null;
  blockName?: string | null;
  blockType: 'solutionSplit';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ProdutosGridBlock".
 */
export interface ProdutosGridBlock {
  eyebrow?: string | null;
  title: string;
  cards: {
    image: number | Media;
    theme: 'on-white' | 'on-navy' | 'on-deep';
    tag?: string | null;
    title: string;
    text: string;
    href?: string | null;
    id?: string | null;
  }[];
  id?: string | null;
  blockName?: string | null;
  blockType: 'produtosGrid';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FeatureGridBlock".
 */
export interface FeatureGridBlock {
  variant?: ('dark' | 'light' | 'rows') | null;
  /**
   * Só com `variant:"dark"` (o variant `light` já é sempre claro). Envolve o grid em `Section light`, fiel a `.why-grid.sec-light` de `_reference/incorporadoras.html`.
   */
  light?: boolean | null;
  /**
   * Só com `light` ativo — troca `.sec-light` por `.sec-light white`.
   */
  white?: boolean | null;
  /**
   * `2` reproduz `.why-grid` (2 colunas); `3` é o grid genérico padrão.
   */
  columns?: ('2' | '3') | null;
  /**
   * Só com `variant:"dark"` (o variant `light` já sempre usa `Stagger`). Troca a entrada por card (`Reveal`) por entrada em grupo (`data-stagger` no ref).
   */
  stagger?: boolean | null;
  eyebrow?: string | null;
  title?: string | null;
  /**
   * Trecho final de `title` a destacar em gradiente, ex.: "em um só contrato." em "Tudo que o condomínio precisa, em um só contrato." Usa `.gx` quando a seção renderiza clara (variant `light` OU `light:true`) e `.gx-ice` quando escura (mesmo padrão de `Benefits.titleAccent`).
   */
  titleAccent?: string | null;
  /**
   * Só com `variant:"rows"`. Parágrafo de apresentação abaixo do `title`, ex.: "Desde 1991, administramos condomínios em Recife..." (`_reference/administradora-de-condominios-recife.html:364`).
   */
  intro?: string | null;
  /**
   * Só com `variant:"rows"`. Link ao fim da lista (`.svc-more`), ex.: "Ver o serviço completo" → `/administracao-de-condominios`.
   */
  moreLink?: {
    label?: string | null;
    href?: string | null;
  };
  features?:
    | {
        /**
         * Glifo/emoji livre — só é renderizado no variant escuro, e só quando `iconSvg` não está preenchido.
         */
        icon?: string | null;
        /**
         * Markup interno do ícone (paths/circles/rects, SEM a tag <svg> em volta), ex.: `<path d="M12 1v22M17 5H9.5a3.5 3.5 0 0 0 0 7h5a3.5 3.5 0 0 1 0 7H6"/>`. No variant claro, renderiza dentro do badge `.ic` (viewBox 24x24, stroke branco, 22x22). No variant escuro, renderiza como glifo nu `.glyph` (viewBox 24x24, stroke ice-400, 34x34) — fiel a `_reference/incorporadoras.html`'s `.why-card .glyph` — e tem prioridade sobre `icon`.
         */
        iconSvg?: string | null;
        title: string;
        /**
         * Não usado no `variant:"rows"` (a linha só tem `title` + `badge` opcional).
         */
        description?: string | null;
        /**
         * Só com `variant:"rows"`. Selo inline ao lado do título da linha, ex.: "EXCLUSIVA"/"1% AO MÊS" (`_reference/administradora-de-condominios-recife.html:368,373`).
         */
        badge?: string | null;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'featureGrid';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "GaranteBlock".
 */
export interface GaranteBlock {
  eyebrow?: string | null;
  title: string;
  text?: string | null;
  video?: (number | null) | Media;
  poster?: (number | null) | Media;
  features?:
    | {
        title: string;
        description: string;
        id?: string | null;
      }[]
    | null;
  cta?: {
    label?: string | null;
    href?: string | null;
  };
  /**
   * Chip de vidro "1%" da banda com vídeo (`.pct-chip`), ex.: valor "1%" + legenda.
   */
  priceChip?: {
    value?: string | null;
    label?: string | null;
  };
  note?: string | null;
  /**
   * Só sem `video`/`poster`. Porcentagem tipográfica gigante da variante split `.g-band` das landings de cidade (`.pct`/`.pct-l`), ex.: valor "1%" + legenda "da arrecadação. Só isso."
   */
  pct?: {
    value?: string | null;
    label?: string | null;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'garante';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CitiesBlock".
 */
export interface CitiesBlock {
  eyebrow?: string | null;
  title?: string | null;
  items?:
    | {
        city: string;
        uf: string;
        role?: string | null;
        image?: (number | null) | Media;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'cities';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "HumanQuoteBlock".
 */
export interface HumanQuoteBlock {
  quote: string;
  author?: string | null;
  image: number | Media;
  caption?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'humanQuote';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "PrestacaoBlock".
 */
export interface PrestacaoBlock {
  eyebrow?: string | null;
  title: string;
  text?: string | null;
  image: number | Media;
  list: {
    icon?: string | null;
    title: string;
    text: string;
    id?: string | null;
  }[];
  id?: string | null;
  blockName?: string | null;
  blockType: 'prestacao';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TecnologiaRoadmapBlock".
 */
export interface TecnologiaRoadmapBlock {
  eyebrow?: string | null;
  title: string;
  text?: string | null;
  intro: {
    /**
     * Opcional. Ex.: semog-one.webp (monitor com o ERP).
     */
    image?: (number | null) | Media;
    name: string;
    description: string;
    tags?:
      | {
          label: string;
          id?: string | null;
        }[]
      | null;
  };
  roadmapLabel?: string | null;
  steps: {
    title: string;
    text: string;
    status: string;
    /**
     * Destaca o status como "no ar" (`.status.live`).
     */
    live?: boolean | null;
    id?: string | null;
  }[];
  id?: string | null;
  blockName?: string | null;
  blockType: 'tecnologiaRoadmap';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ClubeBeneficiosBlock".
 */
export interface ClubeBeneficiosBlock {
  eyebrow?: string | null;
  title: string;
  text?: string | null;
  items: {
    icon?: string | null;
    title: string;
    text: string;
    id?: string | null;
  }[];
  note?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'clubeBeneficios';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "SociosBlock".
 */
export interface SociosBlock {
  eyebrow?: string | null;
  title: string;
  text?: string | null;
  items: {
    title: string;
    text: string;
    id?: string | null;
  }[];
  image: number | Media;
  caption?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'socios';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "RegistrosBlock".
 */
export interface RegistrosBlock {
  title?: string | null;
  light?: boolean | null;
  /**
   * Só com `light` ativo — troca `.sec-light` por `.sec-light white`.
   */
  white?: boolean | null;
  items?:
    | {
        label: string;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'registros';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "AppShowcaseBlock".
 */
export interface AppShowcaseBlock {
  eyebrow?: string | null;
  title: string;
  text?: string | null;
  image?: (number | null) | Media;
  features?:
    | {
        title: string;
        description: string;
        id?: string | null;
      }[]
    | null;
  cta?: {
    label?: string | null;
    href?: string | null;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'appShowcase';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TestimonialsBlock".
 */
export interface TestimonialsBlock {
  eyebrow?: string | null;
  title?: string | null;
  items?:
    | {
        quote: string;
        author: string;
        role?: string | null;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'testimonials';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FaqBlock".
 */
export interface FaqBlock {
  eyebrow?: string | null;
  title?: string | null;
  white?: boolean | null;
  /**
   * Zera o padding-top da seção (`.faq { padding-top: 0 }`, só na família `administracao-de-condominios*` — a seção cola no `.cost`/checklist anterior). `solucoes`/`garante` não têm esse override.
   */
  tightTop?: boolean | null;
  /**
   * Fundo `--bg-deep` escuro em vez de `.sec-light`, fiel a `<section class="faq" style="background:var(--bg-deep)">` de `_reference/garante.html:395` (ao contrário do `.faq.sec-light` claro de `/solucoes`/`administracao-de-condominios`). Sem efeito se `white` também estiver marcado.
   */
  dark?: boolean | null;
  items?:
    | {
        question: string;
        answer: string;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'faq';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CTABandBlock".
 */
export interface CTABandBlock {
  variant?: ('band' | 'centered') | null;
  title: string;
  /**
   * Trecho final de `title` a destacar em gradiente, ex.: "pela líder." em "Seu condomínio administrado pela líder." (`<span class="gx-ice">`, `_reference/administracao-de-condominios.html:380`). Só no variant `centered` — mesmo padrão de `Benefits.titleAccent`/`FeatureGrid.titleAccent`.
   */
  titleAccent?: string | null;
  text?: string | null;
  cta: {
    label: string;
    href: string;
  };
  /**
   * Só no variant `centered`. O `.final-cta` de `_reference/index.html`/`garante.html`/`administracao-de-condominios.html` sempre usa `.btn-white`, mas `_reference/incorporadoras.html:325` usa `.btn-primary` — daí este campo, default `white` para preservar o comportamento das 3 páginas já seedadas.
   */
  buttonVariant?: ('white' | 'primary') | null;
  /**
   * Só no variant `centered`. `max-width` do `.final-cta h2` do ref — a maioria das páginas (`administracao-de-condominios.html`/`incorporadoras.html`/`semog.html`/`solucoes.html`/as 4 landings de cidade) usa `20ch` (o default aqui, sem `font-size` próprio), mas `index.html` usa `16ch` e `garante.html` usa `18ch` — ambas também com `headingFontSize` próprio.
   */
  headingMaxWidth?: string | null;
  /**
   * Só no variant `centered`. `font-size` do `.final-cta h2` do ref, ex.: `clamp(2.4rem, 5.6vw, 4.6rem)` em `index.html`, `clamp(2.2rem, 5vw, 4.2rem)` em `garante.html`. Deixe em branco para o tamanho padrão de `h2` (`--text-h2`) — caso da maioria das páginas.
   */
  headingFontSize?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'ctaBand';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CustoChecklistBlock".
 */
export interface CustoChecklistBlock {
  title: string;
  /**
   * Trecho final de `title` a destacar em gradiente `.gx`, ex.: "administradora?" em "Quanto custa uma administradora?"
   */
  titleAccent?: string | null;
  paragraphs: {
    text: string;
    id?: string | null;
  }[];
  cta: {
    label: string;
    href: string;
  };
  /**
   * Rótulo acima da lista (`.cost-card .top`), ex.: "O que avaliar antes de contratar".
   */
  checklistLabel: string;
  checklist: {
    text: string;
    id?: string | null;
  }[];
  id?: string | null;
  blockName?: string | null;
  blockType: 'custoChecklist';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "RichTextBlock".
 */
export interface RichTextBlock {
  content?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Tratamento `.legal-body` (medida 760px, `h2` compacto, texto em `--text-2`) usado em `/privacidade` e `/termos`. Sem isso marcado, o bloco renderiza como hoje (`Container` sem seção própria).
   */
  legal?: boolean | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'richText';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "BlogListBlock".
 */
export interface BlogListBlock {
  title?: string | null;
  /**
   * Quantidade de posts a exibir (padrão 6).
   */
  limit?: number | null;
  /**
   * Post a excluir da grade — usar o mesmo post do campo "post" de um bloco BlogFeatured logo acima, para não duplicá-lo entre o destaque e a grade. Opcional.
   */
  excludePost?: (number | null) | Post;
  /**
   * Zera o padding-top da seção (mesmo padrão de `Faq.tightTop`/`Pillars.tightTop`) — usar quando este bloco vem logo após um BlogFeatured, pra que os dois pareçam uma única seção clara contínua, fiel a `_reference/blog.html:153-226` (uma só `<section class="sec-light">` para destaque + grade).
   */
  tightTop?: boolean | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'blogList';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts".
 */
export interface Post {
  id: number;
  title: string;
  slug: string;
  heroImage?: (number | null) | Media;
  excerpt?: string | null;
  content?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  category?: (number | null) | Category;
  /**
   * Minutos de leitura estimados — alimenta o "meta" dos cards do blog (ex.: "Equipe Semog · 8 min"), fiel a `_reference/blog.html` (`.featured .meta`/`.post .meta`).
   */
  readingTime?: number | null;
  publishedAt?: string | null;
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories".
 */
export interface Category {
  id: number;
  title: string;
  slug: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "BlogFeaturedBlock".
 */
export interface BlogFeaturedBlock {
  /**
   * Post exibido em destaque (card grande, 2 colunas). Dica: exclua este mesmo post da grade abaixo via o campo "excludePost" do bloco BlogList, para não duplicar.
   */
  post: number | Post;
  id?: string | null;
  blockName?: string | null;
  blockType: 'blogFeatured';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "NewsletterBlock".
 */
export interface NewsletterBlock {
  title: string;
  text?: string | null;
  placeholder?: string | null;
  buttonLabel?: string | null;
  /**
   * Mensagem exibida no lugar do formulário após o "envio" (client-side, sem backend real — fiel ao `onsubmit` inline de `_reference/blog.html:233`).
   */
  successMessage?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'newsletter';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ShowcaseBlock".
 */
export interface ShowcaseBlock {
  eyebrow?: string | null;
  title: string;
  text?: string | null;
  features?:
    | {
        title: string;
        description: string;
        id?: string | null;
      }[]
    | null;
  cta?: {
    label?: string | null;
    href?: string | null;
  };
  mediaSide?: ('left' | 'right') | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'showcase';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "BenefitsBlock".
 */
export interface BenefitsBlock {
  variant?: ('grid' | 'bento') | null;
  eyebrow?: string | null;
  title?: string | null;
  /**
   * Trecho final de `title` a destacar em gradiente (.gx), ex.: "Semog assume." em "O que muda quando a Semog assume." Só no variant bento.
   */
  titleAccent?: string | null;
  items?:
    | {
        title: string;
        description: string;
        /**
         * Número gigante da célula (.num), ex.: "24h". Só no variant bento.
         */
        value?: string | null;
        /**
         * Foto de fundo da célula (c4). Só no variant bento.
         */
        image?: (number | null) | Media;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'benefits';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ContactInfoBlock".
 */
export interface ContactInfoBlock {
  variant?: ('grid' | 'card' | 'units') | null;
  eyebrow?: string | null;
  title?: string | null;
  /**
   * Só na variante `card`. Trecho final de `title` a destacar em `.gx`, ex.: "em Boa Viagem." em "De portas abertas em Boa Viagem." (`_reference/administradora-de-condominios-recife.html:324`) — mesmo padrão de `FeatureGrid.titleAccent`.
   */
  titleAccent?: string | null;
  items?:
    | {
        city: string;
        uf: string;
        address: string;
        phone: string;
        photo?: (number | null) | Media;
        /**
         * Nas variantes `card`/`units`. Em `card`, selo sobre a foto (`.chip liquid-glass`), ex.: "Matriz · PE". Em `units`, texto puro acima do título (`.unit .role`, ex.: "Matriz · Pernambuco" — sem abreviar UF, fiel a `_reference/contato.html:281,296,311,326`).
         */
        chip?: string | null;
        /**
         * Só na variante `card`. Segunda linha do endereço (`<small>` dentro de `<dd>`), ex.: "Boa Viagem · Recife/PE · CEP 51011-000" — `address` vira só a 1ª linha ("Av. Conselheiro Aguiar, 1000 · Sala 501").
         */
        addressDetail?: string | null;
        /**
         * Nas variantes `card`/`units`. Telefone formatado da linha "WhatsApp" do `dl` (ex.: "(81) 9 9999-9999") — distinto do `whatsapp` do bloco (dígitos, usado no link `wa.me`).
         */
        whatsappDisplay?: string | null;
        /**
         * Nas variantes `card`/`units`. Linha "Horário" do `dl`, ex.: "Segunda a sexta, das 8h às 18h".
         */
        hours?: string | null;
        /**
         * Nas variantes `card`/`units`. Link do CTA ("Como chegar" em `card`, "Ver no mapa" em `units`), ex.: "https://maps.google.com/?q=Semog+recife".
         */
        mapsHref?: string | null;
        id?: string | null;
      }[]
    | null;
  whatsapp?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'contactInfo';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FormEmbedBlock".
 */
export interface FormEmbedBlock {
  formType: 'contato' | 'proposta';
  eyebrow?: string | null;
  title?: string | null;
  text?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'formEmbed';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "PriceMomentBlock".
 */
export interface PriceMomentBlock {
  /**
   * Número gigante em gradiente (`.huge`), ex.: "1%".
   */
  value: string;
  sub?: string | null;
  fine?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'priceMoment';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CompareBlock".
 */
export interface CompareBlock {
  title: string;
  before: {
    tag: string;
    items: {
      text: string;
      id?: string | null;
    }[];
  };
  after: {
    tag: string;
    items: {
      text: string;
      id?: string | null;
    }[];
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'compare';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "PartnerSplitBlock".
 */
export interface PartnerSplitBlock {
  title: string;
  text: string;
  /**
   * Trecho de `text` a destacar em `<strong>` navy-500, ex.: "G5 Partners" (`<strong style="color:var(--navy-500);">`, `_reference/garante.html:384`).
   */
  highlight?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'partnerSplit';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "DevQuoteBlock".
 */
export interface DevQuoteBlock {
  /**
   * Aceita `<em>...</em>` embutido para o trecho final em destaque (cor ice) do ref, ex.: "A Semog entrega a convivência." em `_reference/incorporadoras.html:314` (`.dev-quote blockquote em`) — `Words` (mesma primitiva do `WordsSection`) preserva a marcação através do scrub palavra-a-palavra.
   */
  quote: string;
  cite?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'devQuote';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ProcessoTimelineBlock".
 */
export interface ProcessoTimelineBlock {
  eyebrow?: string | null;
  title: string;
  items: {
    /**
     * Markup interno do ícone do dot (paths/circles/rects, SEM a tag <svg> em volta), viewBox 24x24, ex.: `<path d="M3 3v18h18"/><path d="M7 15l4-6 4 3 5-8"/>`. Renderizado stroke ice-400 (#ADD5EB), 22x22, dentro do dot gradiente.
     */
    iconSvg: string;
    title: string;
    text: string;
    tags?:
      | {
          label: string;
          id?: string | null;
        }[]
      | null;
    id?: string | null;
  }[];
  id?: string | null;
  blockName?: string | null;
  blockType: 'processoTimeline';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "BairrosBlock".
 */
export interface BairrosBlock {
  title: string;
  items?:
    | {
        label: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Nota de apoio abaixo dos pills, ex.: "Também atendemos Olinda, Jaboatão dos Guararapes, Paulista, Região Metropolitana do Recife." (`.hood .note` do ref).
   */
  note?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'bairros';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "QuickLinksBlock".
 */
export interface QuickLinksBlock {
  /**
   * O ref sempre mostra exatamente 3 atalhos (WhatsApp/e-mail/proposta) — `.quick-grid` é uma grade fixa de 3 colunas.
   */
  items?:
    | {
        /**
         * Glifo de vidro do card (`.quick-card .ic`), fiel aos 3 SVGs inline de `_reference/contato.html:212,218,224` (WhatsApp/envelope/documento com check).
         */
        icon: 'whatsapp' | 'email' | 'document';
        title: string;
        description: string;
        /**
         * Linha em destaque no fim do card (`.quick-card .val`), ex.: "(81) 9 9999-9999" ou "Solicitar proposta →".
         */
        value: string;
        href: string;
        /**
         * Abre em nova aba (`target="_blank" rel="noopener"`) — o card de WhatsApp do ref usa isso, e-mail (`mailto:`) e o link interno pra `/proposta` não.
         */
        external?: boolean | null;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'quickLinks';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "SelfServeBlock".
 */
export interface SelfServeBlock {
  title: string;
  /**
   * Trecho final de `title` a destacar em `.gx`, ex.: "sem esperar." em "Resolva fácil, sem esperar." (`_reference/contato.html:237`) — mesmo padrão de `FeatureGrid.titleAccent`.
   */
  titleAccent?: string | null;
  text?: string | null;
  items?:
    | {
        title: string;
        description: string;
        href: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Nota de apoio abaixo da grade (`.ss-note`), ex.: "Precisa de outra coisa? O time responde no WhatsApp em horário comercial." (`_reference/contato.html:266`).
   */
  note?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'selfServe';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TrustPanelBlock".
 */
export interface TrustPanelBlock {
  /**
   * Fundo do cartão de estatísticas (`.hero-card`), escurecido por um overlay — `hero-towers.webp` no ref.
   */
  photo?: (number | null) | Media;
  /**
   * Os 4 números do `.trust-stats` (35 / +700 / +70 mil / 4). Números fixos, sem animação de contador — o ref não anima aqui (diferente do `Stats`/`.stats-grid` da home).
   */
  stats?:
    | {
        value: string;
        label: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Citação sobre o Semog Garante (`.trust-quote`), ex.: "Com o Semog Garante, a inadimplência do seu condomínio cai a zero."
   */
  quote: string;
  /**
   * Trecho final de `quote` a destacar (`.trust-quote em`, cor sólida `--ice-400`, sem itálico), ex.: "cai a zero."
   */
  quoteAccent?: string | null;
  quoteText: string;
  whatsappTitle: string;
  /**
   * Texto antes do número, ex.: "Chame no WhatsApp:"
   */
  whatsappText?: string | null;
  /**
   * Dígitos puros, usado no link `https://wa.me/<whatsapp>`.
   */
  whatsapp: string;
  /**
   * Telefone formatado, ex.: "(81) 9 9999-9999".
   */
  whatsappDisplay: string;
  id?: string | null;
  blockName?: string | null;
  blockType: 'trustPanel';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "LegalHeroBlock".
 */
export interface LegalHeroBlock {
  headline: string;
  /**
   * Linha `.upd` abaixo do título, ex.: "Última atualização: julho de 2026 · Documento em revisão pelo jurídico da Semog".
   */
  updatedText?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'legalHero';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "forms".
 */
export interface Form {
  id: number;
  title: string;
  fields?:
    | (
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            required?: boolean | null;
            defaultValue?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'checkbox';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'email';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: number | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'number';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: string | null;
            placeholder?: string | null;
            options?:
              | {
                  label: string;
                  value: string;
                  id?: string | null;
                }[]
              | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'select';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: string | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'text';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: string | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'textarea';
          }
      )[]
    | null;
  submitButtonLabel?: string | null;
  confirmationType?: ('message' | 'redirect') | null;
  confirmationMessage?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  redirect?: {
    url: string;
  };
  emails?:
    | {
        emailTo?: string | null;
        cc?: string | null;
        bcc?: string | null;
        replyTo?: string | null;
        emailFrom?: string | null;
        subject: string;
        message?: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        } | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "form-submissions".
 */
export interface FormSubmission {
  id: number;
  form: number | Form;
  submissionData?:
    | {
        field: string;
        value: string;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'posts';
        value: number | Post;
      } | null)
    | ({
        relationTo: 'categories';
        value: number | Category;
      } | null)
    | ({
        relationTo: 'forms';
        value: number | Form;
      } | null)
    | ({
        relationTo: 'form-submissions';
        value: number | FormSubmission;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  layout?:
    | T
    | {
        hero?: T | HeroBlockSelect<T>;
        stats?: T | StatsBlockSelect<T>;
        valuesMarquee?: T | ValuesMarqueeBlockSelect<T>;
        wordsSection?: T | WordsSectionBlockSelect<T>;
        pillars?: T | PillarsBlockSelect<T>;
        timeline?: T | TimelineBlockSelect<T>;
        solucoesBento?: T | SolucoesBentoBlockSelect<T>;
        solutionSplit?: T | SolutionSplitBlockSelect<T>;
        produtosGrid?: T | ProdutosGridBlockSelect<T>;
        featureGrid?: T | FeatureGridBlockSelect<T>;
        garante?: T | GaranteBlockSelect<T>;
        cities?: T | CitiesBlockSelect<T>;
        humanQuote?: T | HumanQuoteBlockSelect<T>;
        prestacao?: T | PrestacaoBlockSelect<T>;
        tecnologiaRoadmap?: T | TecnologiaRoadmapBlockSelect<T>;
        clubeBeneficios?: T | ClubeBeneficiosBlockSelect<T>;
        socios?: T | SociosBlockSelect<T>;
        registros?: T | RegistrosBlockSelect<T>;
        appShowcase?: T | AppShowcaseBlockSelect<T>;
        testimonials?: T | TestimonialsBlockSelect<T>;
        faq?: T | FaqBlockSelect<T>;
        ctaBand?: T | CTABandBlockSelect<T>;
        custoChecklist?: T | CustoChecklistBlockSelect<T>;
        richText?: T | RichTextBlockSelect<T>;
        blogList?: T | BlogListBlockSelect<T>;
        blogFeatured?: T | BlogFeaturedBlockSelect<T>;
        newsletter?: T | NewsletterBlockSelect<T>;
        showcase?: T | ShowcaseBlockSelect<T>;
        benefits?: T | BenefitsBlockSelect<T>;
        contactInfo?: T | ContactInfoBlockSelect<T>;
        formEmbed?: T | FormEmbedBlockSelect<T>;
        priceMoment?: T | PriceMomentBlockSelect<T>;
        compare?: T | CompareBlockSelect<T>;
        partnerSplit?: T | PartnerSplitBlockSelect<T>;
        devQuote?: T | DevQuoteBlockSelect<T>;
        processoTimeline?: T | ProcessoTimelineBlockSelect<T>;
        bairros?: T | BairrosBlockSelect<T>;
        quickLinks?: T | QuickLinksBlockSelect<T>;
        selfServe?: T | SelfServeBlockSelect<T>;
        trustPanel?: T | TrustPanelBlockSelect<T>;
        legalHero?: T | LegalHeroBlockSelect<T>;
      };
  publishedAt?: T;
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "HeroBlock_select".
 */
export interface HeroBlockSelect<T extends boolean = true> {
  eyebrow?: T;
  headline?: T;
  subhead?: T;
  tag?: T;
  video?: T;
  poster?: T;
  background?: T;
  pageHeroOverlay?: T;
  pageHeroMinHeight?: T;
  pageHeroPosterOpacity?: T;
  pageHeroBgPosition?: T;
  pageHeroGradient?: T;
  pageHeroPaddingBottom?: T;
  pageHeroHeadlineMaxWidth?: T;
  ctas?:
    | T
    | {
        label?: T;
        href?: T;
        variant?: T;
        id?: T;
      };
  priceChip?:
    | T
    | {
        value?: T;
        label?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "StatsBlock_select".
 */
export interface StatsBlockSelect<T extends boolean = true> {
  eyebrow?: T;
  title?: T;
  items?:
    | T
    | {
        value?: T;
        prefix?: T;
        suffix?: T;
        label?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ValuesMarqueeBlock_select".
 */
export interface ValuesMarqueeBlockSelect<T extends boolean = true> {
  variant?: T;
  items?: T;
  separator?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "WordsSectionBlock_select".
 */
export interface WordsSectionBlockSelect<T extends boolean = true> {
  variant?: T;
  eyebrow?: T;
  text?: T;
  sub?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "PillarsBlock_select".
 */
export interface PillarsBlockSelect<T extends boolean = true> {
  eyebrow?: T;
  tightTop?: T;
  light?: T;
  white?: T;
  compact?: T;
  items?:
    | T
    | {
        glyph?: T;
        title?: T;
        text?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TimelineBlock_select".
 */
export interface TimelineBlockSelect<T extends boolean = true> {
  eyebrow?: T;
  title?: T;
  text?: T;
  items?:
    | T
    | {
        date?: T;
        title?: T;
        text?: T;
        image?: T;
        now?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "SolucoesBentoBlock_select".
 */
export interface SolucoesBentoBlockSelect<T extends boolean = true> {
  eyebrow?: T;
  title?: T;
  cards?:
    | T
    | {
        image?: T;
        tag?: T;
        title?: T;
        text?: T;
        href?: T;
        tall?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "SolutionSplitBlock_select".
 */
export interface SolutionSplitBlockSelect<T extends boolean = true> {
  items?:
    | T
    | {
        variant?: T;
        kicker?: T;
        title?: T;
        text?: T;
        tags?:
          | T
          | {
              label?: T;
              id?: T;
            };
        image?: T;
        reversed?: T;
        ctaLabel?: T;
        ctaHref?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ProdutosGridBlock_select".
 */
export interface ProdutosGridBlockSelect<T extends boolean = true> {
  eyebrow?: T;
  title?: T;
  cards?:
    | T
    | {
        image?: T;
        theme?: T;
        tag?: T;
        title?: T;
        text?: T;
        href?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FeatureGridBlock_select".
 */
export interface FeatureGridBlockSelect<T extends boolean = true> {
  variant?: T;
  light?: T;
  white?: T;
  columns?: T;
  stagger?: T;
  eyebrow?: T;
  title?: T;
  titleAccent?: T;
  intro?: T;
  moreLink?:
    | T
    | {
        label?: T;
        href?: T;
      };
  features?:
    | T
    | {
        icon?: T;
        iconSvg?: T;
        title?: T;
        description?: T;
        badge?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "GaranteBlock_select".
 */
export interface GaranteBlockSelect<T extends boolean = true> {
  eyebrow?: T;
  title?: T;
  text?: T;
  video?: T;
  poster?: T;
  features?:
    | T
    | {
        title?: T;
        description?: T;
        id?: T;
      };
  cta?:
    | T
    | {
        label?: T;
        href?: T;
      };
  priceChip?:
    | T
    | {
        value?: T;
        label?: T;
      };
  note?: T;
  pct?:
    | T
    | {
        value?: T;
        label?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CitiesBlock_select".
 */
export interface CitiesBlockSelect<T extends boolean = true> {
  eyebrow?: T;
  title?: T;
  items?:
    | T
    | {
        city?: T;
        uf?: T;
        role?: T;
        image?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "HumanQuoteBlock_select".
 */
export interface HumanQuoteBlockSelect<T extends boolean = true> {
  quote?: T;
  author?: T;
  image?: T;
  caption?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "PrestacaoBlock_select".
 */
export interface PrestacaoBlockSelect<T extends boolean = true> {
  eyebrow?: T;
  title?: T;
  text?: T;
  image?: T;
  list?:
    | T
    | {
        icon?: T;
        title?: T;
        text?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TecnologiaRoadmapBlock_select".
 */
export interface TecnologiaRoadmapBlockSelect<T extends boolean = true> {
  eyebrow?: T;
  title?: T;
  text?: T;
  intro?:
    | T
    | {
        image?: T;
        name?: T;
        description?: T;
        tags?:
          | T
          | {
              label?: T;
              id?: T;
            };
      };
  roadmapLabel?: T;
  steps?:
    | T
    | {
        title?: T;
        text?: T;
        status?: T;
        live?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ClubeBeneficiosBlock_select".
 */
export interface ClubeBeneficiosBlockSelect<T extends boolean = true> {
  eyebrow?: T;
  title?: T;
  text?: T;
  items?:
    | T
    | {
        icon?: T;
        title?: T;
        text?: T;
        id?: T;
      };
  note?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "SociosBlock_select".
 */
export interface SociosBlockSelect<T extends boolean = true> {
  eyebrow?: T;
  title?: T;
  text?: T;
  items?:
    | T
    | {
        title?: T;
        text?: T;
        id?: T;
      };
  image?: T;
  caption?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "RegistrosBlock_select".
 */
export interface RegistrosBlockSelect<T extends boolean = true> {
  title?: T;
  light?: T;
  white?: T;
  items?:
    | T
    | {
        label?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "AppShowcaseBlock_select".
 */
export interface AppShowcaseBlockSelect<T extends boolean = true> {
  eyebrow?: T;
  title?: T;
  text?: T;
  image?: T;
  features?:
    | T
    | {
        title?: T;
        description?: T;
        id?: T;
      };
  cta?:
    | T
    | {
        label?: T;
        href?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TestimonialsBlock_select".
 */
export interface TestimonialsBlockSelect<T extends boolean = true> {
  eyebrow?: T;
  title?: T;
  items?:
    | T
    | {
        quote?: T;
        author?: T;
        role?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FaqBlock_select".
 */
export interface FaqBlockSelect<T extends boolean = true> {
  eyebrow?: T;
  title?: T;
  white?: T;
  tightTop?: T;
  dark?: T;
  items?:
    | T
    | {
        question?: T;
        answer?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CTABandBlock_select".
 */
export interface CTABandBlockSelect<T extends boolean = true> {
  variant?: T;
  title?: T;
  titleAccent?: T;
  text?: T;
  cta?:
    | T
    | {
        label?: T;
        href?: T;
      };
  buttonVariant?: T;
  headingMaxWidth?: T;
  headingFontSize?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CustoChecklistBlock_select".
 */
export interface CustoChecklistBlockSelect<T extends boolean = true> {
  title?: T;
  titleAccent?: T;
  paragraphs?:
    | T
    | {
        text?: T;
        id?: T;
      };
  cta?:
    | T
    | {
        label?: T;
        href?: T;
      };
  checklistLabel?: T;
  checklist?:
    | T
    | {
        text?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "RichTextBlock_select".
 */
export interface RichTextBlockSelect<T extends boolean = true> {
  content?: T;
  legal?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "BlogListBlock_select".
 */
export interface BlogListBlockSelect<T extends boolean = true> {
  title?: T;
  limit?: T;
  excludePost?: T;
  tightTop?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "BlogFeaturedBlock_select".
 */
export interface BlogFeaturedBlockSelect<T extends boolean = true> {
  post?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "NewsletterBlock_select".
 */
export interface NewsletterBlockSelect<T extends boolean = true> {
  title?: T;
  text?: T;
  placeholder?: T;
  buttonLabel?: T;
  successMessage?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ShowcaseBlock_select".
 */
export interface ShowcaseBlockSelect<T extends boolean = true> {
  eyebrow?: T;
  title?: T;
  text?: T;
  features?:
    | T
    | {
        title?: T;
        description?: T;
        id?: T;
      };
  cta?:
    | T
    | {
        label?: T;
        href?: T;
      };
  mediaSide?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "BenefitsBlock_select".
 */
export interface BenefitsBlockSelect<T extends boolean = true> {
  variant?: T;
  eyebrow?: T;
  title?: T;
  titleAccent?: T;
  items?:
    | T
    | {
        title?: T;
        description?: T;
        value?: T;
        image?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ContactInfoBlock_select".
 */
export interface ContactInfoBlockSelect<T extends boolean = true> {
  variant?: T;
  eyebrow?: T;
  title?: T;
  titleAccent?: T;
  items?:
    | T
    | {
        city?: T;
        uf?: T;
        address?: T;
        phone?: T;
        photo?: T;
        chip?: T;
        addressDetail?: T;
        whatsappDisplay?: T;
        hours?: T;
        mapsHref?: T;
        id?: T;
      };
  whatsapp?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FormEmbedBlock_select".
 */
export interface FormEmbedBlockSelect<T extends boolean = true> {
  formType?: T;
  eyebrow?: T;
  title?: T;
  text?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "PriceMomentBlock_select".
 */
export interface PriceMomentBlockSelect<T extends boolean = true> {
  value?: T;
  sub?: T;
  fine?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CompareBlock_select".
 */
export interface CompareBlockSelect<T extends boolean = true> {
  title?: T;
  before?:
    | T
    | {
        tag?: T;
        items?:
          | T
          | {
              text?: T;
              id?: T;
            };
      };
  after?:
    | T
    | {
        tag?: T;
        items?:
          | T
          | {
              text?: T;
              id?: T;
            };
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "PartnerSplitBlock_select".
 */
export interface PartnerSplitBlockSelect<T extends boolean = true> {
  title?: T;
  text?: T;
  highlight?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "DevQuoteBlock_select".
 */
export interface DevQuoteBlockSelect<T extends boolean = true> {
  quote?: T;
  cite?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ProcessoTimelineBlock_select".
 */
export interface ProcessoTimelineBlockSelect<T extends boolean = true> {
  eyebrow?: T;
  title?: T;
  items?:
    | T
    | {
        iconSvg?: T;
        title?: T;
        text?: T;
        tags?:
          | T
          | {
              label?: T;
              id?: T;
            };
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "BairrosBlock_select".
 */
export interface BairrosBlockSelect<T extends boolean = true> {
  title?: T;
  items?:
    | T
    | {
        label?: T;
        id?: T;
      };
  note?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "QuickLinksBlock_select".
 */
export interface QuickLinksBlockSelect<T extends boolean = true> {
  items?:
    | T
    | {
        icon?: T;
        title?: T;
        description?: T;
        value?: T;
        href?: T;
        external?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "SelfServeBlock_select".
 */
export interface SelfServeBlockSelect<T extends boolean = true> {
  title?: T;
  titleAccent?: T;
  text?: T;
  items?:
    | T
    | {
        title?: T;
        description?: T;
        href?: T;
        id?: T;
      };
  note?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TrustPanelBlock_select".
 */
export interface TrustPanelBlockSelect<T extends boolean = true> {
  photo?: T;
  stats?:
    | T
    | {
        value?: T;
        label?: T;
        id?: T;
      };
  quote?: T;
  quoteAccent?: T;
  quoteText?: T;
  whatsappTitle?: T;
  whatsappText?: T;
  whatsapp?: T;
  whatsappDisplay?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "LegalHeroBlock_select".
 */
export interface LegalHeroBlockSelect<T extends boolean = true> {
  headline?: T;
  updatedText?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts_select".
 */
export interface PostsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  heroImage?: T;
  excerpt?: T;
  content?: T;
  category?: T;
  readingTime?: T;
  publishedAt?: T;
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories_select".
 */
export interface CategoriesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "forms_select".
 */
export interface FormsSelect<T extends boolean = true> {
  title?: T;
  fields?:
    | T
    | {
        checkbox?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              required?: T;
              defaultValue?: T;
              id?: T;
              blockName?: T;
            };
        email?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        number?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        select?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              placeholder?: T;
              options?:
                | T
                | {
                    label?: T;
                    value?: T;
                    id?: T;
                  };
              required?: T;
              id?: T;
              blockName?: T;
            };
        text?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        textarea?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
      };
  submitButtonLabel?: T;
  confirmationType?: T;
  confirmationMessage?: T;
  redirect?:
    | T
    | {
        url?: T;
      };
  emails?:
    | T
    | {
        emailTo?: T;
        cc?: T;
        bcc?: T;
        replyTo?: T;
        emailFrom?: T;
        subject?: T;
        message?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "form-submissions_select".
 */
export interface FormSubmissionsSelect<T extends boolean = true> {
  form?: T;
  submissionData?:
    | T
    | {
        field?: T;
        value?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header".
 */
export interface Header {
  id: number;
  navItems?:
    | {
        label: string;
        href: string;
        id?: string | null;
      }[]
    | null;
  cta?: {
    label?: string | null;
    href?: string | null;
  };
  clientArea?: {
    label?: string | null;
    href?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer".
 */
export interface Footer {
  id: number;
  footCta?: {
    slogan?: string | null;
    sloganEm?: string | null;
    cta?: {
      label?: string | null;
      href?: string | null;
    };
  };
  columns?:
    | {
        title: string;
        links?:
          | {
              label: string;
              href: string;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  legalLinks?:
    | {
        label: string;
        href: string;
        id?: string | null;
      }[]
    | null;
  bottomText?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "company".
 */
export interface Company {
  id: number;
  addresses?:
    | {
        city: string;
        uf: string;
        address: string;
        phone?: string | null;
        creci?: string | null;
        abadi?: string | null;
        secovi?: string | null;
        id?: string | null;
      }[]
    | null;
  whatsapp?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSettings {
  id: number;
  defaultTitle?: string | null;
  defaultDescription?: string | null;
  ogImage?: (number | null) | Media;
  social?: {
    instagram?: string | null;
    linkedin?: string | null;
    facebook?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header_select".
 */
export interface HeaderSelect<T extends boolean = true> {
  navItems?:
    | T
    | {
        label?: T;
        href?: T;
        id?: T;
      };
  cta?:
    | T
    | {
        label?: T;
        href?: T;
      };
  clientArea?:
    | T
    | {
        label?: T;
        href?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer_select".
 */
export interface FooterSelect<T extends boolean = true> {
  footCta?:
    | T
    | {
        slogan?: T;
        sloganEm?: T;
        cta?:
          | T
          | {
              label?: T;
              href?: T;
            };
      };
  columns?:
    | T
    | {
        title?: T;
        links?:
          | T
          | {
              label?: T;
              href?: T;
              id?: T;
            };
        id?: T;
      };
  legalLinks?:
    | T
    | {
        label?: T;
        href?: T;
        id?: T;
      };
  bottomText?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "company_select".
 */
export interface CompanySelect<T extends boolean = true> {
  addresses?:
    | T
    | {
        city?: T;
        uf?: T;
        address?: T;
        phone?: T;
        creci?: T;
        abadi?: T;
        secovi?: T;
        id?: T;
      };
  whatsapp?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  defaultTitle?: T;
  defaultDescription?: T;
  ogImage?: T;
  social?:
    | T
    | {
        instagram?: T;
        linkedin?: T;
        facebook?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}